<?php include_once "header.php"; ?>
    <div id="main-layout-container">
    </div>
    <script id="layout-template" type="text/template">
        <div class="container">
            <div id="wide-region" style=""></div>
            <div class="small-widgets near">
                <div id="mini1">
                </div>
                <div id="mini2">
                </div>
            </div>
            <div class="center" id="content-region">
            </div>
        </div>
    </script>

    <!--<div class="library-container widget-container">-->
    <!--</div>-->

    <div class="busy-box">
        <i class="fa fa-spin fa-spinner"></i>
    <span class="message">
        در حال بارگیری...
    </span>
    </div>

    </body>


<?php include_once 'partials/templates.php' ?>
<?php include_once "footer.php"; ?>