<?php include_once "header.php"; ?>
    <div id="layout">
        <div id="top-bar-region"></div>
        <div id="main-container-region"></div>
    </div>

    <template id="layout-template">
    </template>


    <div class="busy-box">
        <i class="fa fa-spin fa-spinner"></i>
    <span class="message">
        در حال بارگیری...
    </span>
    </div>

<?php include_once 'partials/templates.php' ?>
<?php include_once "footer.php"; ?>