<?php
$base = $this->url->getBaseUri();
$development = $this->config->stage == 'development';
?>
<?php //$base = '';?>
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>سامانه مهر</title>
    <!--    <link rel="stylesheet" href="--><? //= $base ?><!--vendor/ext/resources/css/ext-all-gray-rtl-debug.css"/>-->
    <!--    <link rel="stylesheet" href="--><? //= $base ?><!--vendor/ext/resources/css/ext-all-rtl-debug.css"/>-->
    <link rel="stylesheet" href="<?= $base ?>vendor/ext/resources/css/ext-all-neptune-rtl-debug.css"/>
    <link rel="stylesheet" href="<?= $base ?>vendor/ext-ux/ux.css">
    <!--    <link rel="stylesheet" href="vendor/famfamfam/famfamfam.css"/>-->

    <style type="text/css">
        #entityManagement {
            padding: 20px;
            text-align: center;
        }

        .settingIcon {
            height: 128px;
            width: 128px;
            background: url("assets/img/128p/setting.png");
            border: none;
            float: right;
        }

    </style>
</head>

<body>
</body>

<script type="text/javascript">
    BASE = "<?= $base ?>";
</script>

<?php if ($development): ?>
    <script src='<?= $base ?>vendor/ext/ext-all-rtl-debug-w-comments.js'></script>
<?php else: ?>
    <script src='<?= $base ?>vendor/ext/ext-all-rtl.js'></script>
<?php endif; ?>

<script src='<?= $base ?>ahura/utility.js'></script>
<script src='<?= $base ?>mehr/api?javascript'></script>
<script src='<?= $base ?>mehr/js'></script>
    <script src="<?= $base ?>vendor/tinymce/tinymce.min.js"></script>

<?php if ($development): ?>

    <script src="<?= $base ?>vendor/ext/local/ext-lang-fa.js"></script>
    <script src="<?= $base ?>vendor/moment.js"></script>
    <script src="<?= $base ?>vendor/moment-jalaali.js"></script>

<?php else: ?>
    <script src='<?= $base ?>ext.merged.js'></script>
<?php endif; ?>

<script src='<?= $base ?>app/app.js'></script>


</html>
