<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>سامانه مهر</title>
      <link rel="stylesheet" href="vendor/ext/resources/css/ext-all-rtl-debug.css"/>
      <link rel="stylesheet" href="vendor/famfamfam/famfamfam.css"/>
  </head>
  <style type="text/css">
      #entityManagement{
          padding: 20px;
          text-align: center;
      }
      .settingIcon{
          height: 128px;
          width: 128px;
          background: url("assets/img/128p/setting.png");
          border: none;
          float: right;
      }

  </style>
  <body>

  </body>
  <!--<script type="text/javascript" src="vendor/ext/ext-debug-w-comments.js"></script>-->
  <script type="text/javascript" src="vendor/ext/ext-all-rtl-dev.js"></script>
  <script type="text/javascript" src="vendor/ext/local/ext-lang-fa.js"></script>
  <!--<script type="text/javascript" src="vendor/ext/ext-debug.js"></script>-->
  <script type="text/javascript" src="ahura/utility.js"></script>
  <script type="text/javascript" src="ahura/form/combo/SID.js"></script>
  <script type="text/javascript" src="app/app.js"></script>
  <script type="text/javascript" src="app/view/user/Edit.js"></script>
  <script type="text/javascript" src="app/view/user/Window.js"></script>
  <script type="text/javascript" src="app/view/entity/List.js"></script>
  <script type="text/javascript" src="app/view/entity/Edit.js"></script>
  <script type="text/javascript" src="app/view/entity/TermEdit.js"></script>
  <script type="text/javascript" src="app/view/entity/TermsList.js"></script>
  <script type="text/javascript" src="mehr/api?javascript"></script>
  <script type="text/javascript" src="mehr/js"></script>
  <script type="text/javascript" src="vendor/moment.js"></script>
  <script type="text/javascript" src="vendor/moment-jalaali.js"></script>

</html>
