<?php
$base = $this->url->getBaseUri();
$development = $this->config->stage == 'development';
?>
<?php //$base = '';?>
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>سامانه مهر</title>
    <!--    <link rel="stylesheet" href="--><? //= $base ?><!--vendor/ext/resources/css/ext-all-gray-rtl-debug.css"/>-->
    <!--    <link rel="stylesheet" href="--><? //= $base ?><!--vendor/ext/resources/css/ext-all-rtl-debug.css"/>-->
    <link rel="stylesheet" href="<?= $base ?>vendor/ext/resources/css/ext-all-neptune-rtl-debug.css"/>
    <link rel="stylesheet" href="<?= $base ?>vendor/ext-ux/ux.css">
    <!--    <link rel="stylesheet" href="vendor/famfamfam/famfamfam.css"/>-->

    <style type="text/css">
        #entityManagement {
            padding: 20px;
            text-align: center;
        }

        .settingIcon {
            height: 128px;
            width: 128px;
            background: url("assets/img/128p/setting.png");
            border: none;
            float: right;
        }

    </style>
</head>

<body>
<div style="display: none;">
    <div style="padding: 15px;" id="welcomeMsg">
<h1>
    تیریک، شما در آستانه تحول در فرآیندهای فرهنگی هستید.
</h1>
        <b>
            کاربر ارجمند، به محیط آزمایشی سامانه مدیریت امور فرهنگی مهر، خوش‌آمدید. لطفاً پیش از آغاز استفاده به موارد زیر توجه فرمایید:
        </b>
        <ul>
            <li>
                پس از اولین بارگیری، بازدیدهای بعدی از سامانه با سرعت زیاد انجام می‌شود در نسخه نهایی سامانه سریع‌تر نیز بارگذاری می‌شود.
            </li>
            <li>در صورت نیاز به هرگونه راهنمایی لطفاً در ساعات اداری با شماره 02133027920 و در ساعات دیگر با شماره 02180803025 تماس بگیرید. کارشناسان شرکت برای پاسخگویی همیشه حاضر هستند.</li>
            <li>برخی از امکانات سامانه به‌تازگی پیاده‌سازی شده است. در صورت مشاهده هرگونه خطا لطفاً موقعیت ایجاد خطا را به شرکت اطلاع دهید.</li>
            <li>
                برخی امکانات در نسخه نمایشی غیرفعال هستند.
            </li>
            <li>
                توجه داشته باشید که این نرم‌افزار در مراجع قانونی ثبت‌شده است و هرگونه نمونه‌برداری غیرقانونی است و جرم محسوب می‌شود.
            </li>
        </ul>
    </div>
</div>
</body>

<script type="text/javascript">
    BASE = "<?= $base ?>";
</script>

<?php if ($development): ?>
    <script src='<?= $base ?>vendor/ext/ext-all-rtl-debug-w-comments.js'></script>
<?php else: ?>
    <script src='<?= $base ?>vendor/ext/ext-all-rtl.js'></script>
<?php endif; ?>

<script src='<?= $base ?>ahura/utility.js'></script>
<script src='<?= $base ?>mehr/api?javascript'></script>
<script src='<?= $base ?>mehr/js'></script>
<script src="<?= $base ?>vendor/tinymce/tinymce.min.js"></script>

<?php if ($development): ?>

    <script src="<?= $base ?>vendor/ext/local/ext-lang-fa.js"></script>
    <script src="<?= $base ?>vendor/moment.js"></script>
    <script src="<?= $base ?>vendor/moment-jalaali.js"></script>

<?php else: ?>
    <script src='<?= $base ?>ext.merged.js'></script>
<?php endif; ?>

<script src='<?= $base ?>app/app.js'></script>


</html>
