var Ahura= Ahura || {};
cnst=<?= $constants ?>;
Ahura.dev=<?= $this->config->stage == 'development' ? 'true' : 'false' ?>;
Ahura.store= Ahura.store || [];
Ahura.store.ProgramTypes=<?= $programType ?>;
Ahura.store.Degrees=<?= $degree ?>;
Ahura.store.Religion=<?= $religion ?>;
Ahura.store.EntityType=<?= $entityType ?>;
Ahura.store.ProgramSubjects=<?= $subject ?>;
Ahura.store.ProgramLevels=<?= $audienceLevel ?>;
Ahura.store.MembershipType=<?= $membership ?>;
Ahura.store.CouncilMembership=<?= $councilMembership ?>;
Ahura.store.EnrollmentStatus=<?= $enrollmentStatus ?>;
Ahura.store.Nationality=<?= $nationality ?>;
Ahura.store.Courses = <?= $course ?>;
Ahura.store.UserType = <?= $userType ?>;
Ahura.store.Departments = <?= $department ?>;
Ahura.store.Colleges = <?= $college ?>;
Ahura.store.MaritalStatus = <?= $maritalStatus ?>;
Ext.ns('Ahura.button');
Ahura.button.SaveForm = {
itemId: 'saveBtn',
text: 'ذخیره',
icon: icon('save'),
handler: function () {
var c = [], d = [];
var form = this.up('window').down('form').getForm();
var win = this.up('window');
if (form.isValid()) {
// Submit the Ajax request and handle the response
form.submit({
submitEmptyText: false,
params: {},
success: function (form, action) {
//                            Ext.Msg.alert('Success', action.result.message);
Ext.MessageBox.show({
scope: win,
rtl: true,
title: 'موفقیت',
msg: 'دستور شما به درستی اجرا شد.',
//                            msg: 'اطلاعات به شکل موفقیت آمیز ذخیره شد.',
buttons: Ext.MessageBox.OK,
icon: Ext.MessageBox.INFO,
fn: function () {
this.close();
}
})
},
failure: function (form, action) {
var msg = 'ارتباط با سرور برقرار نشد.';
if (action.result) {
if (action.result.message) msg = action.result.message;
msg = 'در داده‌های وارد شده خطا وجود دارد.'
}
Ext.MessageBox.show({
rtl: true,
msg: msg,
title: 'خطا',
buttons: Ext.MessageBox.OK,
icon: Ext.MessageBox.ERROR
});
}
});
} else {
var errors = [];
form.getFields().each(function (field) {
errors = errors.concat(Ext.Array.map(field.getErrors(), function (error) {
return {field: field.getName(), error: error}
}));
});
Ext.MessageBox.show({
rtl: true,
title: 'ورودی نامعتبر',
msg: 'در داده‌های وارد شده خطا وجود دارد.',
buttons: Ext.MessageBox.OK,
icon: Ext.MessageBox.ERROR
});

}
}
};
Ahura.button.CancelForm = {
text: 'انصراف',
itemId: 'cancelBtn',
icon: icon('cancel'),
handler: function () {
this.up('window').close();
}
};


Ahura.store.ProgramStage=[
['c', 'جاری'],
['a', 'پایان‌یافته'],
['b', 'آغازنشده' ]
];

/*
Ahura.store.ProgramLevels = [
['12', "استان"],
['15', "بین الملل"],
['8', "خوابگاه"],
['7', "دانشکده"],
['9', "دانشکده"],
['10', "دانشگاه"],
['11', "شهرستان"],
['14', "کشور"],
['5', "کلاس"],
['6', "گروه آموزشی"],
['13', "منطقه کشوری"]
];

Ahura.store.Colleges = [
['3', "ادبیات و علوم انسانی"],
['4', "الهیات"],
['1', "علوم پایه"],
['5', "علوم تربیتی و روانشناسی"],
['6', "فناوری اطلاعات"],
['2', "فنی و مهندسی"]
];
Ahura.store.Departments = [
['9', "ادیان"],
['23', "برق"],
['7', "تاریخ و تمدن"],
['16', "تربیت بدنی"],
['17', "روانشناسی"],
['12', "ریاضی"],
['1', "زبان و ادبیات انگلیسی"],
['3', "زبان و ادبیات عربی"],
['2', "زبان و ادبیات فارسی"],
['14', "زیست شناسی"],
['10', "شیمی"],
['15', "علوم تربیتی"],
['21', "عمران"],
['4', "فقه و حقوق"],
['5', "فلسفه"],
['20', "فناوری اطلاعات"],
['11', "فیزیک"],
['6', "قرآن"],
['18', "کتابداری"],
['13', "کشاورزی"],
['19', "مطالعات خانواده"],
['8', "معارف"],
['22', "مکانیک"],
['24', "مواد"]
];

Ahura.store.Disciplines = [
['44', "آمورش زبان و ادبیات  ■ کارشناسی ارشد ناپیوسته ■ روزانه"],
['45', "آمورش زبان و ادبیات  ■ کارشناسی ارشد ناپیوسته ■ شبانه"],
['37', "ادیان و عرفان تطبیقی ■ کارشناسی ارشد ناپیوسته ■ روزانه"],
['36', "ادیان و عرفان تطبیقی ■ کارشناسی پیوسته ■ روزانه"],
['71', "امور زراعی ■ کاردانی ناپیوسته ■ روزانه"],
['61', "برق - قدرت ■ کارشناسی پیوسته ■ روزانه"],
['88', "برق- الکترونیک ■ کارشناسی پیوسته ■ دبیری"],
['90', "برق- قدرت ■ کارشناسی ارشد ناپیوسته ■ روزانه"],
['87', "برق- قدرت ■ کارشناسی پیوسته ■ دبیری"]
];

*/
