var Ahura= Ahura || {};
Ahura.store= Ahura.store || [];
Ahura.store.ProgramTypes=<?= $programType ?>;
Ahura.store.Degrees=<?= $degree ?>;
Ahura.store.Religion=<?= $religion ?>;
Ahura.store.EntityType=<?= $entityType ?>;
Ahura.store.ProgramSubjects=<?= $subject ?>;
Ahura.store.ProgramLevels=<?= $audienceLevel ?>;
Ahura.store.MembershipType=<?= $membership ?>;
Ahura.store.CouncilMembership=<?= $councilMembership ?>;
Ahura.store.EnrollmentStatus=<?= $enrollmentStatus ?>;
Ahura.store.Nationality=<?= $nationality ?>;
Ahura.store.Courses = <?= $course ?>;
Ahura.store.UserType = <?= $userType ?>;
Ahura.store.Departments = <?= $department ?>;
Ahura.store.Colleges = <?= $college ?>;

Ahura.store.ProgramStage=[
['c', 'جاری'],
['a', 'پایان‌یافته'],
['b', 'آغازنشده' ]
];

/*
Ahura.store.ProgramLevels = [
['12', "استان"],
['15', "بین الملل"],
['8', "خوابگاه"],
['7', "دانشکده"],
['9', "دانشکده"],
['10', "دانشگاه"],
['11', "شهرستان"],
['14', "کشور"],
['5', "کلاس"],
['6', "گروه آموزشی"],
['13', "منطقه کشوری"]
];

Ahura.store.Colleges = [
['3', "ادبیات و علوم انسانی"],
['4', "الهیات"],
['1', "علوم پایه"],
['5', "علوم تربیتی و روانشناسی"],
['6', "فناوری اطلاعات"],
['2', "فنی و مهندسی"]
];
Ahura.store.Departments = [
['9', "ادیان"],
['23', "برق"],
['7', "تاریخ و تمدن"],
['16', "تربیت بدنی"],
['17', "روانشناسی"],
['12', "ریاضی"],
['1', "زبان و ادبیات انگلیسی"],
['3', "زبان و ادبیات عربی"],
['2', "زبان و ادبیات فارسی"],
['14', "زیست شناسی"],
['10', "شیمی"],
['15', "علوم تربیتی"],
['21', "عمران"],
['4', "فقه و حقوق"],
['5', "فلسفه"],
['20', "فناوری اطلاعات"],
['11', "فیزیک"],
['6', "قرآن"],
['18', "کتابداری"],
['13', "کشاورزی"],
['19', "مطالعات خانواده"],
['8', "معارف"],
['22', "مکانیک"],
['24', "مواد"]
];

Ahura.store.Disciplines = [
['44', "آمورش زبان و ادبیات  ■ کارشناسی ارشد ناپیوسته ■ روزانه"],
['45', "آمورش زبان و ادبیات  ■ کارشناسی ارشد ناپیوسته ■ شبانه"],
['37', "ادیان و عرفان تطبیقی ■ کارشناسی ارشد ناپیوسته ■ روزانه"],
['36', "ادیان و عرفان تطبیقی ■ کارشناسی پیوسته ■ روزانه"],
['71', "امور زراعی ■ کاردانی ناپیوسته ■ روزانه"],
['61', "برق - قدرت ■ کارشناسی پیوسته ■ روزانه"],
['88', "برق- الکترونیک ■ کارشناسی پیوسته ■ دبیری"],
['90', "برق- قدرت ■ کارشناسی ارشد ناپیوسته ■ روزانه"],
['87', "برق- قدرت ■ کارشناسی پیوسته ■ دبیری"]
];

*/
Ahura.store.Terms =[];
for(var i=moment().jYear()-10;i<=moment().jYear()+1;i++){
Ahura.store.Terms.push(i+'03');
Ahura.store.Terms.push(i+'06');
Ahura.store.Terms.push(i+'11');
}