INSERT INTO `mehr3`.`constant` (`category`) VALUES ('postType');
SELECT LAST_INSERT_ID();
SELECT `id`, `text`, `value`, `category` FROM `mehr3`.`constant` WHERE  `id`=135;
UPDATE `mehr3`.`constant` SET `value`='program' WHERE  `id`=133;
SELECT `id`, `text`, `value`, `category` FROM `mehr3`.`constant` WHERE  `id`=133;
UPDATE `mehr3`.`constant` SET `value`='news' WHERE  `id`=134;
SELECT `id`, `text`, `value`, `category` FROM `mehr3`.`constant` WHERE  `id`=134;
UPDATE `mehr3`.`constant` SET `value`='entity' WHERE  `id`=135;
SELECT `id`, `text`, `value`, `category` FROM `mehr3`.`constant` WHERE  `id`=135;
UPDATE `mehr3`.`constant` SET `text`='برنامه' WHERE  `id`=133;
SELECT `id`, `text`, `value`, `category` FROM `mehr3`.`constant` WHERE  `id`=133;
UPDATE `mehr3`.`constant` SET `text`='خبر' WHERE  `id`=134;
SELECT `id`, `text`, `value`, `category` FROM `mehr3`.`constant` WHERE  `id`=134;
UPDATE `mehr3`.`constant` SET `text`='نهاد' WHERE  `id`=135;
SELECT `id`, `text`, `value`, `category` FROM `mehr3`.`constant` WHERE  `id`=135;
INSERT INTO `mehr3`.`constant` (`text`, `value`, `category`) VALUES ('نشریه', 'issue', 'postType');