CREATE TABLE `vote` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`userId` INT NOT NULL DEFAULT '0',
	`candidateId` INT NOT NULL DEFAULT '0',
	`councilId` INT NOT NULL DEFAULT '0',
	`cDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_persian_ci'
ENGINE=InnoDB;